version: '3.7'
x-defaults: &defaults
  tty: true
  stdin_open: true
  build:
    context: .
    cache_from:
      - ruby:2.5.1-alpine
      - pushtocite_test
      - pushtocite
      - nyulibraries/pushtocite
      - nyulibraries/pushtocite:$BRANCH_NO_SLASH
  image: pushtocite_test

services:
  dev:
    <<: *defaults
    ports:
      - "9292:9292"
    environment:
      UNICORN_PORT: "9292"
      CI:
    # volumes:
      # - ./app:/app/app
      # - ./public:/app/public
