version: '3.7'
x-defaults: &defaults
  tty: true
  stdin_open: true
  build:
    context: .
  image: pushtocite

services:
  dev:
    <<: *defaults
    ports:
      - "9292:9292"
    environment:
      UNICORN_PORT: "9292"
    volumes:
      - ./app:/app/app

  test:
    <<: *defaults
    command: ["bundle", "exec", "rspec"]

  prod:
    build:
      context: .
      args:
        BUNDLE_WITHOUT: "no_docker development test"
    image: pushtocite_prod