version: '3.2'
services:

  dev:
    build:
      context: .
    image: pushtocite
    # volumes:
      # - .:/app
    ports:
      - "9292:9292"
    command: ["bundle", "exec", "unicorn", "-p", "9292", "-c", "./config/unicorn.rb"]
