version: '3.2'
services:

  dev:
    tty: true
    stdin_open: true
    build:
      context: .
    image: pushtocite
    ports:
      - "9292:9292"
    volumes:
      - ./app:/app/app
    environment:
      RACK_ENV: development
    command: ["bundle", "exec", "rackup", "-o", "0.0.0.0"]

  prod:
    build:
      context: .
    image: pushtocite
    ports:
      - "9292:9292"
    command: ["bundle", "exec", "unicorn", "-p", "9292", "-c", "./config/unicorn.rb"]
