version: '3.7'
x-defaults: &defaults
  tty: true
  stdin_open: true
  build:
    context: .
    cache_from:
      - ruby:2.5.1-alpine
      - pushtocite_test
      - pushtocite
      - quay.io/nyulibraries/pushtocite
      - quay.io/nyulibraries/pushtocite:$BRANCH_NO_SLASH
    args:
      RUN_PACKAGES: "git"
      ADDL_BUILD_PACKAGES: ""
  image: pushtocite_test

services:
  dev:
    <<: *defaults
    ports:
      - 9292:9292
    environment:
      UNICORN_PORT: "9292"
      CI:
      COVERALLS_REPO_TOKEN:
      PRIMO_BASE_URL: http://primodev1.bobst.nyu.edu
      TERM: xterm
      PAGER: more
    volumes:
      - ./:/app
    command: rerun 'rackup --host 0.0.0.0 -p 9292'
    # command: rackup --host 0.0.0.0 -p 9292
#     networks:
#       - custom

# networks:
#   custom:
#     external: true